// Generated by npm run db:types from clean migrations. Do not edit.
export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = { public: {
  Tables: {
    admin_memberships: {
      Row: {
        user_id: string;
        role: string;
        granted_by: string | null;
        granted_at: string;
      };
      Insert: {
        user_id: string;
        role: string;
        granted_by?: string | null;
        granted_at?: string;
      };
      Update: {
        user_id?: string;
        role?: string;
        granted_by?: string | null;
        granted_at?: string;
      };
      Relationships: [

      ];
    };
    connector_evidence: {
      Row: {
        id: string;
        connector_id: string;
        run_id: string;
        external_id: string;
        source_url: string;
        content_hash: string;
        parser_version: string;
        storage_path: string;
        content_type: string;
        byte_count: number;
        fetched_at: string;
        expires_at: string;
        created_at: string;
      };
      Insert: {
        id?: string;
        connector_id: string;
        run_id: string;
        external_id: string;
        source_url: string;
        content_hash: string;
        parser_version: string;
        storage_path: string;
        content_type: string;
        byte_count: number;
        fetched_at: string;
        expires_at: string;
        created_at?: string;
      };
      Update: {
        id?: string;
        connector_id?: string;
        run_id?: string;
        external_id?: string;
        source_url?: string;
        content_hash?: string;
        parser_version?: string;
        storage_path?: string;
        content_type?: string;
        byte_count?: number;
        fetched_at?: string;
        expires_at?: string;
        created_at?: string;
      };
      Relationships: [
        { foreignKeyName: "connector_evidence_connector_id_fkey"; columns: ["connector_id"]; isOneToOne: false; referencedRelation: "source_connectors"; referencedColumns: ["id"] },
        { foreignKeyName: "connector_evidence_run_id_fkey"; columns: ["run_id"]; isOneToOne: false; referencedRelation: "sync_runs"; referencedColumns: ["id"] },
      ];
    };
    connector_host_budgets: {
      Row: {
        host: string;
        window_start: string;
        requests: number;
        daily_limit: number;
        min_interval_ms: number;
        next_request_at: string;
        holder: string | null;
        held_until: string | null;
      };
      Insert: {
        host: string;
        window_start: string;
        requests?: number;
        daily_limit: number;
        min_interval_ms: number;
        next_request_at?: string;
        holder?: string | null;
        held_until?: string | null;
      };
      Update: {
        host?: string;
        window_start?: string;
        requests?: number;
        daily_limit?: number;
        min_interval_ms?: number;
        next_request_at?: string;
        holder?: string | null;
        held_until?: string | null;
      };
      Relationships: [

      ];
    };
    duplicate_reviews: {
      Row: {
        id: string;
        event_a_id: string;
        event_b_id: string;
        signals: Json;
        status: string;
        decision_reason: string | null;
        decided_by: string | null;
        decided_at: string | null;
        pre_merge_snapshot: Json | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        event_a_id: string;
        event_b_id: string;
        signals: Json;
        status?: string;
        decision_reason?: string | null;
        decided_by?: string | null;
        decided_at?: string | null;
        pre_merge_snapshot?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        event_a_id?: string;
        event_b_id?: string;
        signals?: Json;
        status?: string;
        decision_reason?: string | null;
        decided_by?: string | null;
        decided_at?: string | null;
        pre_merge_snapshot?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [
        { foreignKeyName: "duplicate_reviews_event_a_id_fkey"; columns: ["event_a_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        { foreignKeyName: "duplicate_reviews_event_b_id_fkey"; columns: ["event_b_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
      ];
    };
    event_categories: {
      Row: {
        id: string;
        slug: string;
        name: string;
      };
      Insert: {
        id?: string;
        slug: string;
        name: string;
      };
      Update: {
        id?: string;
        slug?: string;
        name?: string;
      };
      Relationships: [

      ];
    };
    event_changes: {
      Row: {
        id: string;
        event_id: string;
        event_version: number;
        actor_id: string | null;
        source_id: string | null;
        reason: string;
        field_diff: Json;
        evidence_snapshot: Json;
        created_at: string;
      };
      Insert: {
        id?: string;
        event_id: string;
        event_version: number;
        actor_id?: string | null;
        source_id?: string | null;
        reason: string;
        field_diff: Json;
        evidence_snapshot: Json;
        created_at?: string;
      };
      Update: {
        id?: string;
        event_id?: string;
        event_version?: number;
        actor_id?: string | null;
        source_id?: string | null;
        reason?: string;
        field_diff?: Json;
        evidence_snapshot?: Json;
        created_at?: string;
      };
      Relationships: [
        { foreignKeyName: "event_changes_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        { foreignKeyName: "event_changes_source_id_fkey"; columns: ["source_id"]; isOneToOne: false; referencedRelation: "event_sources"; referencedColumns: ["id"] },
      ];
    };
    event_deadlines: {
      Row: {
        id: string;
        event_id: string;
        kind: string;
        label: string;
        local_date: string | null;
        due_at: string | null;
        timezone: string | null;
        precision: string;
        source_id: string | null;
        active: boolean;
        is_primary: boolean;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        event_id: string;
        kind: string;
        label: string;
        local_date?: string | null;
        due_at?: string | null;
        timezone?: string | null;
        precision?: string;
        source_id?: string | null;
        active?: boolean;
        is_primary?: boolean;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        event_id?: string;
        kind?: string;
        label?: string;
        local_date?: string | null;
        due_at?: string | null;
        timezone?: string | null;
        precision?: string;
        source_id?: string | null;
        active?: boolean;
        is_primary?: boolean;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [
        { foreignKeyName: "event_deadlines_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        { foreignKeyName: "event_deadlines_source_id_event_id_fkey"; columns: ["source_id","event_id"]; isOneToOne: false; referencedRelation: "event_sources"; referencedColumns: ["id","event_id"] },
      ];
    };
    event_sources: {
      Row: {
        id: string;
        event_id: string | null;
        connector_id: string;
        external_id: string;
        source_url: string;
        normalized_url: string;
        raw_storage_ref: string | null;
        content_hash: string | null;
        parser_version: string | null;
        last_attempt_at: string | null;
        last_checked_at: string | null;
        source_updated_at: string | null;
        availability: string;
        validated_observation: Json | null;
        field_evidence: Json | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        event_id?: string | null;
        connector_id: string;
        external_id: string;
        source_url: string;
        normalized_url: string;
        raw_storage_ref?: string | null;
        content_hash?: string | null;
        parser_version?: string | null;
        last_attempt_at?: string | null;
        last_checked_at?: string | null;
        source_updated_at?: string | null;
        availability?: string;
        validated_observation?: Json | null;
        field_evidence?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        event_id?: string | null;
        connector_id?: string;
        external_id?: string;
        source_url?: string;
        normalized_url?: string;
        raw_storage_ref?: string | null;
        content_hash?: string | null;
        parser_version?: string | null;
        last_attempt_at?: string | null;
        last_checked_at?: string | null;
        source_updated_at?: string | null;
        availability?: string;
        validated_observation?: Json | null;
        field_evidence?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [
        { foreignKeyName: "event_sources_connector_id_fkey"; columns: ["connector_id"]; isOneToOne: false; referencedRelation: "source_connectors"; referencedColumns: ["id"] },
        { foreignKeyName: "event_sources_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
      ];
    };
    event_tags: {
      Row: {
        event_id: string;
        tag: string;
        kind: string;
        skill_id: string | null;
      };
      Insert: {
        event_id: string;
        tag: string;
        kind: string;
        skill_id?: string | null;
      };
      Update: {
        event_id?: string;
        tag?: string;
        kind?: string;
        skill_id?: string | null;
      };
      Relationships: [
        { foreignKeyName: "event_tags_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        { foreignKeyName: "event_tags_skill_id_tag_fkey"; columns: ["skill_id","tag"]; isOneToOne: false; referencedRelation: "skills"; referencedColumns: ["id","slug"] },
      ];
    };
    events: {
      Row: {
        id: string;
        slug: string;
        title: string;
        short_description: string | null;
        full_description: string | null;
        participation_process: string | null;
        organizer_id: string | null;
        category_id: string | null;
        official_url: string | null;
        registration_url: string | null;
        image_url: string | null;
        image_rights: Json | null;
        start_date: string | null;
        end_date: string | null;
        start_at: string | null;
        end_at: string | null;
        timezone: string | null;
        date_precision: string;
        date_metadata: Json | null;
        mode: string | null;
        venue: string | null;
        city: string | null;
        state: string | null;
        country: string | null;
        latitude: number | null;
        longitude: number | null;
        eligibility_text: string | null;
        eligibility_rules: Json | null;
        eligible_years: number[] | null;
        eligible_degrees: string[] | null;
        individual_allowed: boolean | null;
        min_team_size: number | null;
        max_team_size: number | null;
        fee: number | null;
        fee_max: number | null;
        fee_status: string;
        fee_basis: string;
        currency: string | null;
        prize_pool: number | null;
        prize_currency: string | null;
        prize_description: string | null;
        status: string;
        registration_status: string;
        publication_status: string;
        verification_level: string | null;
        verification_status: string;
        last_checked_at: string | null;
        source_updated_at: string | null;
        version: number;
        created_at: string;
        updated_at: string;
        merged_into_event_id: string | null;
        search_vector: string | null;
      };
      Insert: {
        id?: string;
        slug: string;
        title: string;
        short_description?: string | null;
        full_description?: string | null;
        participation_process?: string | null;
        organizer_id?: string | null;
        category_id?: string | null;
        official_url?: string | null;
        registration_url?: string | null;
        image_url?: string | null;
        image_rights?: Json | null;
        start_date?: string | null;
        end_date?: string | null;
        start_at?: string | null;
        end_at?: string | null;
        timezone?: string | null;
        date_precision?: string;
        date_metadata?: Json | null;
        mode?: string | null;
        venue?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        eligibility_text?: string | null;
        eligibility_rules?: Json | null;
        eligible_years?: number[] | null;
        eligible_degrees?: string[] | null;
        individual_allowed?: boolean | null;
        min_team_size?: number | null;
        max_team_size?: number | null;
        fee?: number | null;
        fee_max?: number | null;
        fee_status?: string;
        fee_basis?: string;
        currency?: string | null;
        prize_pool?: number | null;
        prize_currency?: string | null;
        prize_description?: string | null;
        status?: string;
        registration_status?: string;
        publication_status?: string;
        verification_level?: string | null;
        verification_status?: string;
        last_checked_at?: string | null;
        source_updated_at?: string | null;
        version?: number;
        created_at?: string;
        updated_at?: string;
        merged_into_event_id?: string | null;
        search_vector?: never;
      };
      Update: {
        id?: string;
        slug?: string;
        title?: string;
        short_description?: string | null;
        full_description?: string | null;
        participation_process?: string | null;
        organizer_id?: string | null;
        category_id?: string | null;
        official_url?: string | null;
        registration_url?: string | null;
        image_url?: string | null;
        image_rights?: Json | null;
        start_date?: string | null;
        end_date?: string | null;
        start_at?: string | null;
        end_at?: string | null;
        timezone?: string | null;
        date_precision?: string;
        date_metadata?: Json | null;
        mode?: string | null;
        venue?: string | null;
        city?: string | null;
        state?: string | null;
        country?: string | null;
        latitude?: number | null;
        longitude?: number | null;
        eligibility_text?: string | null;
        eligibility_rules?: Json | null;
        eligible_years?: number[] | null;
        eligible_degrees?: string[] | null;
        individual_allowed?: boolean | null;
        min_team_size?: number | null;
        max_team_size?: number | null;
        fee?: number | null;
        fee_max?: number | null;
        fee_status?: string;
        fee_basis?: string;
        currency?: string | null;
        prize_pool?: number | null;
        prize_currency?: string | null;
        prize_description?: string | null;
        status?: string;
        registration_status?: string;
        publication_status?: string;
        verification_level?: string | null;
        verification_status?: string;
        last_checked_at?: string | null;
        source_updated_at?: string | null;
        version?: number;
        created_at?: string;
        updated_at?: string;
        merged_into_event_id?: string | null;
        search_vector?: never;
      };
      Relationships: [
        { foreignKeyName: "events_category_id_fkey"; columns: ["category_id"]; isOneToOne: false; referencedRelation: "event_categories"; referencedColumns: ["id"] },
        { foreignKeyName: "events_merged_into_event_id_fkey"; columns: ["merged_into_event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
        { foreignKeyName: "events_organizer_id_fkey"; columns: ["organizer_id"]; isOneToOne: false; referencedRelation: "organizers"; referencedColumns: ["id"] },
      ];
    };
    interests: {
      Row: {
        id: string;
        slug: string;
        name: string;
      };
      Insert: {
        id?: string;
        slug: string;
        name: string;
      };
      Update: {
        id?: string;
        slug?: string;
        name?: string;
      };
      Relationships: [

      ];
    };
    organizers: {
      Row: {
        id: string;
        name: string;
        website: string | null;
        normalized_identity: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        name: string;
        website?: string | null;
        normalized_identity: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        name?: string;
        website?: string | null;
        normalized_identity?: string;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [

      ];
    };
    profiles: {
      Row: {
        user_id: string;
        name: string | null;
        institution: string | null;
        degree: string | null;
        study_year: number | null;
        city: string | null;
        country: string | null;
        preferred_categories: string[] | null;
        any_category: boolean | null;
        preferred_modes: string[] | null;
        willingness_to_travel: boolean | null;
        preferred_team_min: number | null;
        preferred_team_max: number | null;
        portfolio_links: string[] | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        user_id: string;
        name?: string | null;
        institution?: string | null;
        degree?: string | null;
        study_year?: number | null;
        city?: string | null;
        country?: string | null;
        preferred_categories?: string[] | null;
        any_category?: boolean | null;
        preferred_modes?: string[] | null;
        willingness_to_travel?: boolean | null;
        preferred_team_min?: number | null;
        preferred_team_max?: number | null;
        portfolio_links?: string[] | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        user_id?: string;
        name?: string | null;
        institution?: string | null;
        degree?: string | null;
        study_year?: number | null;
        city?: string | null;
        country?: string | null;
        preferred_categories?: string[] | null;
        any_category?: boolean | null;
        preferred_modes?: string[] | null;
        willingness_to_travel?: boolean | null;
        preferred_team_min?: number | null;
        preferred_team_max?: number | null;
        portfolio_links?: string[] | null;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [

      ];
    };
    saved_events: {
      Row: {
        user_id: string;
        event_id: string;
        created_at: string;
      };
      Insert: {
        user_id: string;
        event_id: string;
        created_at?: string;
      };
      Update: {
        user_id?: string;
        event_id?: string;
        created_at?: string;
      };
      Relationships: [
        { foreignKeyName: "saved_events_event_id_fkey"; columns: ["event_id"]; isOneToOne: false; referencedRelation: "events"; referencedColumns: ["id"] },
      ];
    };
    skills: {
      Row: {
        id: string;
        slug: string;
        name: string;
      };
      Insert: {
        id?: string;
        slug: string;
        name: string;
      };
      Update: {
        id?: string;
        slug?: string;
        name?: string;
      };
      Relationships: [

      ];
    };
    source_connectors: {
      Row: {
        id: string;
        name: string;
        source_url: string;
        type: string;
        enabled: boolean;
        permission_state: string;
        permission_evidence: Json | null;
        policy_metadata: Json | null;
        permission_review_expires_at: string | null;
        last_sync: string | null;
        last_successful_sync: string | null;
        status: string;
        error_count: number;
        next_due_at: string | null;
        lease_token: string | null;
        lease_expires_at: string | null;
        fencing_token: number;
        checkpoint: Json | null;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        name: string;
        source_url: string;
        type: string;
        enabled?: boolean;
        permission_state?: string;
        permission_evidence?: Json | null;
        policy_metadata?: Json | null;
        permission_review_expires_at?: string | null;
        last_sync?: string | null;
        last_successful_sync?: string | null;
        status?: string;
        error_count?: number;
        next_due_at?: string | null;
        lease_token?: string | null;
        lease_expires_at?: string | null;
        fencing_token?: number;
        checkpoint?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        name?: string;
        source_url?: string;
        type?: string;
        enabled?: boolean;
        permission_state?: string;
        permission_evidence?: Json | null;
        policy_metadata?: Json | null;
        permission_review_expires_at?: string | null;
        last_sync?: string | null;
        last_successful_sync?: string | null;
        status?: string;
        error_count?: number;
        next_due_at?: string | null;
        lease_token?: string | null;
        lease_expires_at?: string | null;
        fencing_token?: number;
        checkpoint?: Json | null;
        created_at?: string;
        updated_at?: string;
      };
      Relationships: [

      ];
    };
    sync_runs: {
      Row: {
        id: string;
        connector_id: string;
        trigger: string;
        started_at: string;
        finished_at: string | null;
        status: string;
        discovered_count: number;
        processed_count: number;
        failed_count: number;
        cursor_start: Json | null;
        cursor_end: Json | null;
        error_summary: string | null;
        item_errors: Json | null;
        error_overflow_ref: string | null;
        lease_token: string | null;
        fencing_token: number | null;
        parser_version: string | null;
        policy_snapshot: Json | null;
        request_count: number;
      };
      Insert: {
        id?: string;
        connector_id: string;
        trigger: string;
        started_at?: string;
        finished_at?: string | null;
        status?: string;
        discovered_count?: number;
        processed_count?: number;
        failed_count?: number;
        cursor_start?: Json | null;
        cursor_end?: Json | null;
        error_summary?: string | null;
        item_errors?: Json | null;
        error_overflow_ref?: string | null;
        lease_token?: string | null;
        fencing_token?: number | null;
        parser_version?: string | null;
        policy_snapshot?: Json | null;
        request_count?: number;
      };
      Update: {
        id?: string;
        connector_id?: string;
        trigger?: string;
        started_at?: string;
        finished_at?: string | null;
        status?: string;
        discovered_count?: number;
        processed_count?: number;
        failed_count?: number;
        cursor_start?: Json | null;
        cursor_end?: Json | null;
        error_summary?: string | null;
        item_errors?: Json | null;
        error_overflow_ref?: string | null;
        lease_token?: string | null;
        fencing_token?: number | null;
        parser_version?: string | null;
        policy_snapshot?: Json | null;
        request_count?: number;
      };
      Relationships: [
        { foreignKeyName: "sync_runs_connector_id_fkey"; columns: ["connector_id"]; isOneToOne: false; referencedRelation: "source_connectors"; referencedColumns: ["id"] },
      ];
    };
    user_interests: {
      Row: {
        user_id: string;
        interest_id: string;
      };
      Insert: {
        user_id: string;
        interest_id: string;
      };
      Update: {
        user_id?: string;
        interest_id?: string;
      };
      Relationships: [
        { foreignKeyName: "user_interests_interest_id_fkey"; columns: ["interest_id"]; isOneToOne: false; referencedRelation: "interests"; referencedColumns: ["id"] },
      ];
    };
    user_skills: {
      Row: {
        user_id: string;
        skill_id: string;
      };
      Insert: {
        user_id: string;
        skill_id: string;
      };
      Update: {
        user_id?: string;
        skill_id?: string;
      };
      Relationships: [
        { foreignKeyName: "user_skills_skill_id_fkey"; columns: ["skill_id"]; isOneToOne: false; referencedRelation: "skills"; referencedColumns: ["id"] },
      ];
    };
  };
  Views: {
    public_event_sources: {
      Row: {
        id: string | null;
        event_id: string | null;
        source_url: string | null;
        last_checked_at: string | null;
        source_name: string | null;
      };
      Relationships: [

      ];
    };
  };
  Functions: {
    connector_runtime: { Args: { command: Json }; Returns: Json };
    for_you_candidates: { Args: Record<string, never>; Returns: Json };
    mutate_event: { Args: { command: Json }; Returns: Json };
    save_profile_section: { Args: { section: string; values_json: Json }; Returns: boolean };
    search_published_events: { Args: { filters: Json; page_after: Json }; Returns: Json };
  };
  Enums: { [_ in never]: never };
  CompositeTypes: { [_ in never]: never };
} };
