import { DiscoveryShell,EventCard } from "./public-events";
import type { ForYouResult,RankedCard } from "../lib/for-you/ranking";
function Cards({items}:{items:RankedCard[]}){return <ul className="mt-6 grid gap-8 md:grid-cols-2">{items.map(item=><li key={item.event.id} className="min-w-0"><EventCard event={item.event} headingLevel={3}/><div className="space-y-3 border-t border-border pb-6 pt-4"><p className="font-semibold">{item.eligibility==="eligible"?"Appears eligible":"Eligibility unknown"}</p>{item.score!==null&&<p>Match: {item.score}%</p>}<p>Evidence coverage: {Math.round(item.coverage*100)}% ({item.coverageLevel})</p><h4 className="font-semibold">{item.score===null?"What to review":"Why this matches"}</h4><ul className="list-disc space-y-2 pl-5">{item.reasons.map((reason,i)=><li key={i}>{reason}</li>)}</ul></div></li>)}</ul>;}
export function ForYouContent({value}:{value:ForYouResult}){return <DiscoveryShell authenticated><h1 className="text-4xl font-semibold">For You</h1><p className="mt-4 max-w-3xl">Matches use your recorded profile and published event facts. They are not admission predictions. Official rules remain authoritative.</p>{value.kind!=="ready"?<p className="my-10">Personalized opportunities are temporarily unavailable. Please retry.</p>:<>
 {value.missingSections.length>0&&<section className="mt-8 border border-border p-5"><h2 className="text-xl font-semibold">Complete more of your profile to improve your recommendations.</h2><p className="mt-2">Sections to review: {value.missingSections.join(", ")}.</p><a className="inline-flex min-h-11 items-center underline" href="/account/profile">Review your profile</a><p>Profile completion is not eligibility or evidence coverage.</p></section>}
 <p className="mt-8 text-sm text-muted-foreground">This view evaluates up to 100 candidates selected by recorded preferences, then event date and stable event ID. It is not a ranking of the entire catalogue. Refresh to use current facts; there are no additional ranked pages.</p>
 {!value.hasPublished?<section className="my-10"><h2 className="text-2xl font-semibold">No opportunities are available yet.</h2><p>Published opportunities will appear after review.</p></section>:<>
 <section className="mt-10" aria-labelledby="best-heading"><h2 id="best-heading" className="text-2xl font-semibold">Best Matches</h2>{value.best.length?<Cards items={value.best}/>:<p className="mt-4">No strong matches yet. Explore all opportunities.</p>}</section>
 {value.review.length>0&&<section className="mt-10" aria-labelledby="review-heading"><h2 id="review-heading" className="text-2xl font-semibold">Worth Reviewing</h2><p className="mt-3">Eligibility or scoring evidence needs confirmation. These are not recommendations.</p><Cards items={value.review}/></section>}
 </>}
 </>}<nav aria-label="Personalized actions" className="mt-8 flex flex-wrap gap-5 underline"><a href="/explore">Explore all opportunities</a><a href="/account/profile">Edit profile</a></nav></DiscoveryShell>;}
