import test,{before,after} from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import ts from "typescript";
import {replay} from "../database/harness.mjs";
const source=await readFile(new URL("../../src/lib/events/validation.ts",import.meta.url),"utf8");
const validationUrl="data:text/javascript;base64,"+Buffer.from(ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString("base64");
const {validateCommand,validEligibility}=await import(validationUrl);
let db;const ADMIN="10000000-0000-0000-0000-000000000003",USER="10000000-0000-0000-0000-000000000001",ORG="50000000-0000-0000-0000-000000000001",CON="40000000-0000-0000-0000-000000000001";
let category;
before(async()=>{db=await replay();await db.exec(`insert into auth.users(id)values('${ADMIN}'),('${USER}');insert into public.admin_memberships(user_id,role)values('${ADMIN}','admin');insert into public.organizers(id,name,normalized_identity)values('${ORG}','ISOLATED TEST organizer','isolated-test');insert into public.source_connectors(id,name,source_url,type)values('${CON}','ISOLATED TEST ONLY','https://example.test','feed');insert into public.interests(slug,name)values('robotics','Robotics');insert into public.skills(slug,name)values('python','Python');`);category=(await db.query("select id from public.event_categories where slug='hackathon'")).rows[0].id;});
after(async()=>db?.close());
async function isolated(fn,uid=ADMIN,role="authenticated"){await db.exec("begin");try{await db.exec("set local role "+role);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[uid??""]);await fn();}finally{await db.exec("rollback");}}
async function rpc(command){return (await db.query("select public.mutate_event($1::jsonb) value",[JSON.stringify(command)])).rows[0].value;}
const draft=(patch={})=>({action:"create",reason:"Isolated test",event:{slug:"isolated-event",title:"ISOLATED TEST ONLY",...patch}});
const edit=(e,action="update",extra={})=>({id:e.id,expected_version:e.version,action,reason:"Isolated test change",...extra});
async function reject(command,code){await db.exec("savepoint reject");await assert.rejects(()=>rpc(command),e=>e.code===code);await db.exec("rollback to savepoint reject");}
async function publishable(){let e=await rpc(draft({short_description:"Test summary",organizer_id:ORG,category_id:category,official_url:"https://example.test/event",registration_url:"https://example.test/register",verification_status:"current",verification_level:"community_submitted",last_checked_at:"2026-09-16T00:00:00Z"}));await db.query(`insert into public.event_sources(event_id,connector_id,external_id,source_url,normalized_url,last_checked_at,validated_observation,field_evidence)values($1,$2,'test','https://example.test/event','https://example.test/event',now(),'{"official_url":"https://example.test/event","registration_url":"https://example.test/register"}','{"official_url":{"status":"checked"},"registration_url":{"status":"checked"}}')`,[e.id,CON]);return rpc(edit(e,"review"));}
async function visible(id){await db.exec("set local role anon");const rows=(await db.query("select id from public.events where id=$1",[id])).rows;await db.exec("set local role authenticated");return rows.length;}

test("C05 ordinary user cannot create/update/publish even when calling RPC directly",()=>isolated(async()=>{for(const action of ["create","update","publish"])await reject({...draft(),action},"P0503");},USER));
test("C05 anonymous cannot execute event command",()=>isolated(async()=>{await reject(draft(),"42501");},null,"anon"));
test("C05 admin creates valid draft with null unknown facts and audit",()=>isolated(async()=>{const e=await rpc(draft());assert.equal(e.version,1);assert.equal(e.fee,null);assert.equal(e.individual_allowed,null);assert.equal(e.publication_status,"draft");assert.equal(await visible(e.id),0);const h=(await db.query("select * from public.event_changes where event_id=$1",[e.id])).rows[0];assert.equal(h.actor_id,ADMIN);assert.equal(h.event_version,1);assert.equal(h.field_diff.title.after,"ISOLATED TEST ONLY");}));
test("C05 correct version updates, stale version conflicts, immutable slug",()=>isolated(async()=>{const e=await rpc(draft());const next=await rpc(edit(e,"update",{event:{title:"Changed"}}));assert.equal(next.version,2);await reject(edit(e,"update",{event:{title:"Lost edit"}}),"P0509");await reject(edit(next,"update",{event:{slug:"new-slug"}}),"P0522");assert.equal((await db.query("select title from public.events where id=$1",[e.id])).rows[0].title,"Changed");}));
test("C05 state changes must follow review before publish",()=>isolated(async()=>{const e=await rpc(draft());await reject(edit(e,"publish"),"P0522");}));
test("C05 publish without checked evidence fails and rolls back event and audit",()=>isolated(async()=>{let e=await rpc(draft({short_description:"Summary",organizer_id:ORG,category_id:category,official_url:"https://example.test/event",registration_url:"https://example.test/register",verification_status:"current",verification_level:"community_submitted",last_checked_at:"2026-09-16T00:00:00Z"}));e=await rpc(edit(e,"review"));await reject(edit(e,"publish"),"23514");assert.equal((await db.query("select version from public.events where id=$1",[e.id])).rows[0].version,e.version);assert.equal((await db.query("select count(*)::int n from public.event_changes where event_id=$1",[e.id])).rows[0].n,2);}));
test("C05 valid publish is public; unpublish hides; archive terminal; evidence history retained",()=>isolated(async()=>{let e=await publishable();e=await rpc(edit(e,"publish"));assert.equal(await visible(e.id),1);const h=(await db.query("select evidence_snapshot from public.event_changes where event_id=$1 and event_version=$2",[e.id,e.version])).rows[0];assert.equal(h.evidence_snapshot.sources.length,1);e=await rpc(edit(e,"unpublish"));assert.equal(await visible(e.id),0);e=await rpc(edit(e,"archive"));assert.equal(e.publication_status,"archived");await reject(edit(e,"update",{event:{title:"Reopen"}}),"P0522");}));
test("C05 stale/conflicted verification cannot publish",()=>isolated(async()=>{let e=await publishable();e=await rpc(edit(e,"update",{event:{verification_status:"conflicted"}}));await reject(edit(e,"publish"),"P0512");}));
test("C05 invalid child mutation rolls back parent version/history",()=>isolated(async()=>{const e=await rpc(draft());await reject(edit(e,"update",{event:{title:"Should roll back"},tags:[{kind:"domain",tag:"not-in-vocabulary"}]}),"P0522");assert.equal((await db.query("select title from public.events where id=$1",[e.id])).rows[0].title,e.title);assert.equal((await db.query("select count(*)::int n from public.event_changes where event_id=$1",[e.id])).rows[0].n,1);}));
const deadline={kind:"registration",label:"Registration",local_date:"2026-10-01",due_at:null,timezone:null,precision:"date_only",source_id:null,active:true,is_primary:true};
test("C05 date-only deadlines remain date-only; one primary; child updates advance version and history",()=>isolated(async()=>{let e=await rpc(draft());e=await rpc(edit(e,"update",{deadlines:[deadline]}));let d=(await db.query("select * from public.event_deadlines where event_id=$1",[e.id])).rows[0];assert.equal(d.due_at,null);assert.equal(d.timezone,null);await reject(edit(e,"update",{deadlines:[deadline,{...deadline,label:"Other"}]}),"23505");const {event_id,created_at,updated_at,...input}=d;void event_id;void updated_at;input.local_date="2026-10-02";e=await rpc(edit(e,"update",{deadlines:[input]}));d=(await db.query("select * from public.event_deadlines where event_id=$1",[e.id])).rows[0];assert.equal(String(d.created_at),String(created_at));assert.equal(e.version,3);const h=(await db.query("select field_diff from public.event_changes where event_id=$1 and event_version=3",[e.id])).rows[0];assert.ok(h.field_diff.deadlines);}));
test("C05 deadlines reject another event's source and deadline identity",()=>isolated(async()=>{const a=await publishable();const b=await rpc(draft({slug:"other-event"}));const s=(await db.query("select id from public.event_sources where event_id=$1",[a.id])).rows[0].id;await reject(edit(b,"update",{deadlines:[{...deadline,source_id:s}]}),"23503");await reject(edit(b,"update",{deadlines:[{...deadline,id:ORG}]}),"P0522");}));
test("C05 category and organizer FKs plus controlled tags",()=>isolated(async()=>{await reject(draft({category_id:ORG}),"23503");await reject(draft({organizer_id:ADMIN}),"23503");const skill=(await db.query("select id from public.skills where slug='python'")).rows[0].id;let e=await rpc(draft());e=await rpc(edit(e,"update",{tags:[{kind:"domain",tag:"robotics",skill_id:null},{kind:"skill",tag:"python",skill_id:skill}]}));assert.equal((await db.query("select count(*)::int n from public.event_tags where event_id=$1",[e.id])).rows[0].n,2);await reject(edit(e,"update",{tags:[{kind:"skill",tag:"wrong",skill_id:skill}]}),"23503");}));
test("C05 membership revocation is rechecked for each RPC",()=>isolated(async()=>{const e=await rpc(draft());await db.exec("reset role");await db.query("delete from public.admin_memberships where user_id=$1",[ADMIN]);await db.exec("set local role authenticated");await reject(edit(e,"update",{event:{title:"Forbidden"}}),"P0503");}));
test("C05 audit remains append-only",()=>isolated(async()=>{const e=await rpc(draft());await db.exec("savepoint immutable");await assert.rejects(()=>db.query("update public.event_changes set reason='tamper' where event_id=$1",[e.id]),x=>x.code==="42501");await db.exec("rollback to savepoint immutable;reset role;savepoint owner_tamper");await assert.rejects(()=>db.query("delete from public.event_changes where event_id=$1",[e.id]),x=>x.code==="23514");await db.exec("rollback to savepoint owner_tamper");}));
test("C05 database rejects invalid URL/team/amount/date/category values",()=>isolated(async()=>{for(const patch of [{official_url:"javascript:alert(1)"},{min_team_size:5,max_team_size:2},{fee:1},{date_precision:"date_only",start_date:"2026-09-16",start_at:"2026-09-16T00:00:00Z"}])await reject(draft(patch),"23514");await db.exec("savepoint category");await assert.rejects(()=>db.query("insert into public.event_categories(slug,name)values('job','Job')"),e=>e.code==="23514");await db.exec("rollback to savepoint category");}));
test("C05 runtime validation rejects malformed fields and preserves unknowns",()=>{const good=draft();assert.ok(validateCommand(good).command);const patches=[{title:" "},{mode:["online"]},{official_url:"http://example.test"},{official_url:"https://user:password@example.test"},{date_precision:"date_only",start_date:"2026-02-30"},{min_team_size:3,max_team_size:2},{fee:-1},{fee:0,fee_status:"unknown"},{fee:1.111,currency:"INR",fee_status:"paid"},{eligible_years:[]},{individual_allowed:"false"},{verification_status:null},{category_id:"workshop"},{start_at:"2026-09-16T00:00:00",date_precision:"datetime"},{latitude:91},{timezone:"Invalid/Zone"}];for(const p of patches)assert.ok(validateCommand(draft(p)).issues.length,JSON.stringify(p));const unknown=validateCommand(draft({fee:null,individual_allowed:null,eligible_years:null}));assert.equal(unknown.command.event.individual_allowed,null);});
test("C05 runtime validates date-zone alignment and preserves date-only deadlines",()=>{assert.ok(validateCommand({...draft(),deadlines:[deadline]}).command);assert.ok(validateCommand({...draft(),deadlines:[deadline,deadline]}).issues.length);assert.ok(validateCommand(draft({date_precision:"datetime",start_at:"2026-10-01T22:00:00Z",start_date:"2026-10-01",timezone:"Asia/Kolkata"})).issues.length);assert.ok(validateCommand(draft({date_precision:"datetime",start_at:"2026-10-01T22:00:00Z",start_date:"2026-10-02",timezone:"Asia/Kolkata"})).command);});
test("C05 eligibility validates structure without evaluating or defaulting unknown",()=>{assert.ok(validEligibility({version:1,expression:{op:"unresolved",reason:"Evidence incomplete"}}));assert.ok(validEligibility({version:1,expression:{op:"predicate",field:"study_year",operator:"in",value:[1,2],evidence:"source-rule"}}));for(const v of [{version:1,expression:{op:"all",rules:[]}},{version:1,expression:{op:"predicate",field:"age",operator:"eq",value:18,evidence:"source"}},{version:1,expression:{op:"predicate",field:"degree",operator:"eq",value:"BTech"}},{version:2,expression:{op:"unresolved",reason:"Unknown"}}])assert.equal(validEligibility(v),false);});
// Exercise the actual service authorization boundary independently of page guards.
const serviceSource=(await readFile(new URL("../../src/lib/events/service.ts",import.meta.url),"utf8")).replace('import "server-only";','').replace('"./validation"',JSON.stringify(validationUrl));
const svc=await import("data:text/javascript;base64,"+Buffer.from(ts.transpileModule(serviceSource,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString("base64"));
test("C05 application service rechecks identity/membership before every mutation",async()=>{let allowed=false,rpcs=0,checks=0;const client={auth:{getUser:async()=>({data:{user:{id:ADMIN,email_confirmed_at:"yes"}}})},from:()=>({select(){return this;},eq(){return this;},async maybeSingle(){checks++;return {data:allowed?{role:"admin"}:null};}}),rpc:async()=>{rpcs++;return {data:{id:ORG}};}};for(const action of ["create","update","publish"])assert.equal((await svc.mutateEvent(client,{...draft(),action})).code,"forbidden");allowed=true;assert.equal((await svc.mutateEvent(client,draft())).ok,true);allowed=false;assert.equal((await svc.mutateEvent(client,draft())).code,"forbidden");assert.equal(rpcs,1);assert.equal(checks,5);});

test("C05 pending duplicate review blocks publication",()=>isolated(async()=>{const e=await publishable();const other=await rpc(draft({slug:"other-edition"}));const [a,b]=[e.id,other.id].sort();await db.query("insert into public.duplicate_reviews(event_a_id,event_b_id,signals)values($1,$2,'{}')",[a,b]);await reject(edit(e,"publish"),"P0512");}));
test("C05 explicit critical source conflicts block publication",()=>isolated(async()=>{const e=await publishable();await db.query(`update public.event_sources set field_evidence=field_evidence||'{"fee":{"status":"conflicted"}}' where event_id=$1`,[e.id]);await reject(edit(e,"publish"),"P0512");}));
test("C05 simultaneous edits using one expected version cannot both win",()=>isolated(async()=>{const e=await rpc(draft());await db.exec("savepoint race");const outcomes=await Promise.allSettled([rpc(edit(e,"update",{event:{title:"First contender"}})),rpc(edit(e,"update",{event:{title:"Second contender"}}))]);assert.equal(outcomes.filter(x=>x.status==="fulfilled").length,1);assert.equal(outcomes.find(x=>x.status==="rejected").reason.code,"P0509");await db.exec("rollback to savepoint race");}));

test("C05 service maps atomic database conflicts and publication errors without exposing details",async()=>{let code="P0509";const client={auth:{getUser:async()=>({data:{user:{id:ADMIN,email_confirmed_at:"yes"}}})},from:()=>({select(){return this;},eq(){return this;},async maybeSingle(){return {data:{role:"admin"}};}}),rpc:async()=>({error:{code,message:"Private SQL diagnostic must not escape"}})};assert.deepEqual(await svc.mutateEvent(client,draft()),{ok:false,code:"version_conflict"});code="P0512";assert.deepEqual(await svc.mutateEvent(client,draft()),{ok:false,code:"publication_requirements"});});

// Run the public reader against actual RLS through a narrow in-process PostgREST-shaped adapter.
const publicStub="data:text/javascript,"+encodeURIComponent(`export function createClient(url,key,options){return globalThis.__c05PublicClient(url,key,options);}`);
const envStub="data:text/javascript,"+encodeURIComponent(`export function getPublicSupabaseEnv(){return {url:"https://example.test",key:"sb_publishable_TEST_ONLY"};}`);
const publicSource=(await readFile(new URL("../../src/lib/events/public.ts",import.meta.url),"utf8")).replace('import "server-only";','').replace('"@supabase/supabase-js"',JSON.stringify(publicStub)).replace('"../supabase/public-env"',JSON.stringify(envStub)).replace('"./validation"',JSON.stringify(validationUrl));
const pub=await import("data:text/javascript;base64,"+Buffer.from(ts.transpileModule(publicSource,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText).toString("base64"));
test("C05 public read service uses anonymous context, supports id/slug and exposes only safe source fields",()=>isolated(async()=>{
 globalThis.__c05PublicClient=(url,key,options)=>{assert.equal(key,"sb_publishable_TEST_ONLY");assert.equal(options.auth.persistSession,false);return {from(table){assert.ok(["events","public_event_sources"].includes(table));const filters=[];let selection="";const query={select(s){selection=s;return this;},eq(k,v){assert.ok(["id","slug","publication_status","version","event_id"].includes(k));filters.push([k,v]);return this;},async execute(single){await db.exec("set local role anon");try{const rows=(await db.query("select * from public."+table+" where "+filters.map(([k],i)=>k+"=$"+(i+1)).join(" and "),filters.map(([,v])=>v))).rows;if(table==="events"&&rows[0]&&selection.includes("organizers")){const e=rows[0];e.organizers=(await db.query("select id,name,website from public.organizers where id=$1",[e.organizer_id])).rows[0]??null;e.event_categories=(await db.query("select id,slug,name from public.event_categories where id=$1",[e.category_id])).rows[0]??null;e.event_tags=(await db.query("select tag,kind,skill_id from public.event_tags where event_id=$1",[e.id])).rows;e.event_deadlines=(await db.query("select id,kind,label,local_date,due_at,timezone,precision,source_id,active,is_primary from public.event_deadlines where event_id=$1",[e.id])).rows;}return {data:single?rows[0]??null:rows,error:null};}finally{await db.exec("set local role authenticated");}},maybeSingle(){return this.execute(true);},then(resolve,reject){return this.execute(false).then(resolve,reject);}};return query;}};};
 try {let e=await publishable();assert.equal((await pub.readPublishedEvent({id:e.id})).code,"not_found");e=await rpc(edit(e,"publish"));const read=await pub.readPublishedEvent({slug:e.slug});assert.equal(read.ok,true);assert.equal(read.value.id,e.id);assert.equal(read.value.organizers.id,ORG);assert.equal(read.value.registration_deadline,null);assert.deepEqual(Object.keys(read.value.sources[0]).sort(),["id","event_id","source_url","last_checked_at","source_name"].sort());assert.equal((await pub.readPublishedEvent({id:e.id})).ok,true);await rpc(edit(e,"unpublish"));assert.equal((await pub.readPublishedEvent({slug:e.slug})).code,"not_found");}finally{delete globalThis.__c05PublicClient;}
}));
