// Actual public detail template + C14 section, isolated data and production CSS.
import assert from "node:assert/strict";
import {readFile,readdir} from "node:fs/promises";
import {createServer} from "node:http";
import {createElement} from "react";
import {renderToStaticMarkup} from "react-dom/server";
import {chromium} from "@playwright/test";
import {fixtures,loadComponents} from "../tests/events/c06-harness.mjs";
import {load,profile,event,doc,all,pred} from "../tests/recommendations/harness.mjs";
const {evaluateRecommendation}=await import(await load('src/lib/recommendations/scoring.ts'));
const {EventPersonalization}=await import(await load('src/components/event-personalization.tsx'));
let f,browser,server;
try{
 f=await fixtures();const components=await loadComponents();const detail=(await f.api.readPublishedEvent({slug:'isolated-event-1'})).value;
 const p=profile(),e=event();let deep=pred('degree','eq','BTech');for(let i=0;i<12;i++)deep=all(deep);
 const cases={anonymous:{kind:'anonymous'},eligible:{kind:'ready',result:evaluateRecommendation(p,e)},ineligible:{kind:'ready',result:evaluateRecommendation({...p,study_year:9},e)},unknown:{kind:'ready',result:evaluateRecommendation({...p,degree:null},e)},low:{kind:'ready',result:evaluateRecommendation({...p,interests:null,skills:null},e)},partial:{kind:'ready',result:evaluateRecommendation({},e)},nested:{kind:'ready',result:evaluateRecommendation(p,{...e,eligibility_rules:doc(deep)})},unavailable:{kind:'unavailable'}};
 const css=(await Promise.all((await readdir('.next/static/chunks')).filter(n=>n.endsWith('.css')).map(n=>readFile('.next/static/chunks/'+n,'utf8')))).join('\n');
 server=createServer((req,res)=>{const key=new URL(req.url,'http://local').searchParams.get('case')??'anonymous';res.setHeader('Content-Type','text/html; charset=utf-8');res.end('<!doctype html><html lang="en"><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>'+css+'</style></head><body><a href="#main-content" class="sr-only focus:not-sr-only">Skip to content</a>'+renderToStaticMarkup(createElement(components.EventDetailContent,{event:detail,personalization:createElement(EventPersonalization,{value:cases[key]??cases.anonymous})}))+'</body></html>');});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;browser=await chromium.launch();const page=await browser.newPage();
 for(const width of [320,390,768,1280]){await page.setViewportSize({width,height:900});for(const key of Object.keys(cases)){await page.goto(origin+'/events/isolated-event-1?case='+key);for(const summary of await page.locator('main summary').all())await summary.click();assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),width+' '+key+' no overflow');assert.equal(await page.getByText(/^Match: \d+%$/).count(),cases[key].kind==='ready'&&cases[key].result.score!==null?1:0);assert.ok(await page.getByRole('heading',{name:'Participation & eligibility'}).isVisible());if(key==='anonymous'){assert.equal(await page.getByText('Your eligibility and match',{exact:true}).count(),0);assert.ok(await page.getByText(/Sign in and complete your profile/).isVisible());}if(key==='ineligible')assert.ok(await page.getByText('Appears ineligible',{exact:true}).isVisible());if(key==='unknown'||key==='partial')assert.ok(await page.getByText('Eligibility unknown',{exact:true}).isVisible());if(key==='low')assert.ok(await page.getByText('Not enough information to calculate a reliable match.',{exact:true}).isVisible());}console.log('PASS C14 detail states, explanations and no overflow: '+width+'px');}
 await page.goto(origin+'/events/isolated-event-1?case=eligible');await page.keyboard.press('Tab');assert.equal(await page.locator(':focus').textContent(),'Skip to content');await page.keyboard.press('Enter');const summary=page.getByText('Eligibility reasons and alternatives',{exact:true});await summary.focus();await page.keyboard.press('Enter');assert.equal(await summary.locator('..').getAttribute('open'),'');assert.notEqual(await summary.evaluate(n=>getComputedStyle(n).outlineStyle),'none');assert.ok(await page.getByText(/Pass: Your recorded study year/).isVisible());await page.getByRole('link',{name:'Review or complete your profile'}).focus();assert.equal(await page.locator(':focus').getAttribute('href'),'/account/profile');console.log('PASS C14 keyboard disclosure, visible focus, textual state labels and profile link');
}finally{await browser?.close();if(server)await new Promise(r=>server.close(r));await f?.close();}
