import {test,before,after} from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {replay} from "../database/harness.mjs";
import {parseProfileForm,validProfileUrl,completeness} from "../../src/lib/profiles/validation.ts";
const A="13000000-0000-0000-0000-000000000001",B="13000000-0000-0000-0000-000000000002";
let db,interest,skill;
before(async()=>{db=await replay();await db.query("insert into auth.users(id) values($1),($2)",[A,B]);await db.query("insert into public.profiles(user_id) values($1),($2)",[A,B]);interest=(await db.query("select id from public.interests where slug='robotics'")).rows[0].id;skill=(await db.query("select id from public.skills where slug='python'")).rows[0].id;});
after(async()=>db?.close());
async function as(role,id,fn){await db.exec('begin');try{await db.exec('set local role '+role);await db.query("select set_config('request.jwt.claim.sub',$1,true)",[id??'']);return await fn();}finally{await db.exec('rollback');}}
const save=(section,values)=>db.query('select public.save_profile_section($1,$2::jsonb)',[section,JSON.stringify(values)]);
const own=async()=> (await db.query('select * from public.profiles')).rows[0];
for(const [label,sql] of [['read','select * from public.profiles'],['update',"update public.profiles set name='bad'"],['RPC',"select public.save_profile_section('about','{}')"]])test('anonymous profile '+label+' denied',()=>as('anon',null,()=>assert.rejects(db.query(sql),{code:'42501'})));
test('own read and update use auth.uid through invoker RLS',()=>as('authenticated',A,async()=>{assert.equal((await own()).user_id,A);await save('about',{name:'Student',city:'Pune',country:'IN'});assert.equal((await own()).name,'Student');assert.equal((await db.query('select * from public.profiles where user_id=$1',[B])).rows.length,0);assert.equal((await db.query("update public.profiles set name='bad' where user_id=$1 returning *",[B])).rows.length,0);}));
test('C04 bootstrap ignore-duplicates preserves existing profile',()=>as('authenticated',A,async()=>{await save('about',{name:'Keep'});await db.query('insert into public.profiles(user_id) values($1) on conflict(user_id) do nothing',[A]);assert.equal((await own()).name,'Keep');}));
test('partial onboarding, skip and clearing preserve unknown fields',()=>as('authenticated',A,async()=>{await save('about',{name:'Only a name'});const p=await own();for(const k of ['city','country','degree','study_year','willingness_to_travel','preferred_modes','portfolio_links'])assert.equal(p[k],null);await save('about',{name:null});assert.equal((await own()).name,null);await save('education',{});assert.equal((await own()).study_year,null);}));
for(const [section,table,fk,getId] of [['interests','user_interests','interest_id',()=>interest],['skills','user_skills','skill_id',()=>skill]]){
 test(section+' add, deduplicate, remove atomically',()=>as('authenticated',A,async()=>{const id=getId();await save(section,{ids:[id,id]});assert.equal((await db.query('select * from public.'+table)).rows.length,1);await save(section,{ids:[]});assert.equal((await db.query('select * from public.'+table)).rows.length,0);}));
 test(section+' invalid ID rejects and rolls back existing selection',()=>as('authenticated',A,async()=>{await save(section,{ids:[getId()]});await db.exec('savepoint before_bad');await assert.rejects(save(section,{ids:[B]}),{code:'23503'});await db.exec('rollback to before_bad');assert.equal((await db.query('select * from public.'+table)).rows.length,1);}));
 test(section+' cross-user read/edit/insert denied',()=>as('authenticated',A,async()=>{await db.exec('reset role');await db.query(`insert into public.${table} values($1,$2)`,[B,getId()]);await db.exec('set local role authenticated');assert.equal((await db.query('select * from public.'+table)).rows.length,0);assert.equal((await db.query(`delete from public.${table} where user_id=$1 returning *`,[B])).rows.length,0);await assert.rejects(db.query(`insert into public.${table} values($1,$2)`,[B,getId()]),{code:'42501'});}));
 test(section+' duplicate relationship rejected by primary key',()=>as('authenticated',A,async()=>{await save(section,{ids:[getId()]});await assert.rejects(db.query(`insert into public.${table}(user_id,${fk}) values($1,$2)`,[A,getId()]),{code:'23505'});}));
}
for(const [label,section,values] of [['year','education',{study_year:0}],['fractional year','education',{study_year:1.5}],['country','about',{country:'IND'}],['URL','links',{portfolio_links:['javascript:alert(1)']}],['URL credentials','links',{portfolio_links:['https://user:pass@example.test']}],['mode','preferences',{preferred_modes:['teleport']}],['category','preferences',{preferred_categories:['bad']}],['travel','preferences',{willingness_to_travel:'false'}],['team range','preferences',{preferred_team_min:4,preferred_team_max:2}],['empty preference array','preferences',{preferred_modes:[]}],['owner injection','about',{user_id:B}],['long name','about',{name:'x'.repeat(101)}]])test('database rejects invalid '+label,()=>as('authenticated',A,()=>assert.rejects(save(section,values))));
test('preferences preserve explicit false and null; links removable',()=>as('authenticated',A,async()=>{await save('preferences',{willingness_to_travel:false,any_category:true});assert.equal((await own()).willingness_to_travel,false);assert.equal((await own()).preferred_categories,null);await save('links',{portfolio_links:['https://github.com/test-only']});await save('links',{portfolio_links:null});assert.equal((await own()).portfolio_links,null);}));
test('normal users cannot extend controlled vocabularies',()=>as('authenticated',A,()=>assert.rejects(db.query("insert into public.interests(slug,name) values('invented','Invented')"),{code:'42501'})));
test('RPC is invoker-only and preserves existing bootstrap responsibility',async()=>{const r=(await db.query("select prosecdef from pg_proc where proname='save_profile_section'")).rows[0];assert.equal(r.prosecdef,false);await as('authenticated',A,async()=>{await db.query('delete from public.profiles where user_id=$1',[A]);await assert.rejects(save('about',{name:'Missing'}),{code:'22023'});});});
test('input normalization preserves degree descriptions and does not infer year',()=>{const p=parseProfileForm(new URLSearchParams({section:'education',degree:' B.Tech ',study_year:''}));assert.equal(p.values.degree,'B.Tech');assert.equal(p.values.study_year,null);const c=parseProfileForm(new URLSearchParams({section:'about',country:'in'}));assert.equal(c.values.country,'IN');});
for(const value of ['javascript:alert(1)','data:text/html,bad','file:///tmp/a','https://user:pass@example.test','bad','https://example.test\\evil','https://example.test:99999'])test('runtime rejects URL '+value,()=>assert.equal(validProfileUrl(value),false));
test('runtime IDs/enums/duplicate scalar/owner rejected',()=>{for(const v of [{section:'skills',ids:'wrong'},{section:'preferences',willingness_to_travel:'maybe'},{section:'about',user_id:B}])assert.throws(()=>parseProfileForm(new URLSearchParams(v)));assert.throws(()=>parseProfileForm(new URLSearchParams('section=about&name=a&name=b')));});
test('completeness is deterministic five sections, not matching',async()=>{const p=await as('authenticated',A,own);const x=completeness(p,[],[]);assert.equal(x.completed,0);assert.equal(x.total,5);assert.deepEqual(x,completeness(p,[],[]));p.name='A';p.city='Pune';p.country='IN';assert.equal(completeness(p,[interest],[skill]).completed,3);assert.ok(!('score' in x));});
test('public Explore/detail code never imports profile reads',async()=>{for(const path of ['src/lib/events/public.ts','src/lib/events/public-search.ts','src/app/explore/page.tsx','src/app/events/[slug]/page.tsx'])assert.doesNotMatch(await readFile(path,'utf8'),/readOwnProfile|from\(["']profiles|lib\/profiles/);});
